export const COX_PH_REGRESSION = "COX_PH_REGRESSION";
export const COX_REGRESSION_TIMEDEPENDENT = "COX_REGRESSION_TIMEDEPENDENT";
export const COUNT_PROCESS_ANALYSIS = "COUNT_PROCESS_ANALYSIS";
export const COMPETING_RISK = "COMPETING_RISK";
